name: VALIDATE

on:
  push:

jobs:
  debug-build:
    strategy:
      matrix:
        CONTAINER: [ 'gcc', 'clang', 'icx', 'icc' ]

    runs-on: ubuntu-latest
    container: xzzx/devel:${{ matrix.CONTAINER }}
    steps:
      - name: versions
        run: |
          cat /etc/os-release
          echo $PATH
          git --version
          cmake --version
          $CC --version
          $CXX --version

      - uses: actions/checkout@v2
        with:
          path: 'assumption'

      - name: configuration
        run: cmake -S assumption -B assumption-build -DCMAKE_BUILD_TYPE=Debug

      - name: build dependencies
        run: cmake --build assumption-build --target fmt gmock gmock_main gtest gtest_main -j 2

      - name: build
        run: cmake --build assumption-build --target all -j 2

      - name: test
        working-directory: assumption-build
        run: ctest --output-on-failure -j 2

  release-build:
    strategy:
      matrix:
        CONTAINER: [ 'gcc', 'clang', 'icx', 'icc' ]

    runs-on: ubuntu-latest
    container: xzzx/devel:${{ matrix.CONTAINER }}
    steps:
      - name: versions
        run: |
          cat /etc/os-release
          echo $PATH
          git --version
          cmake --version
          $CC --version
          $CXX --version

      - uses: actions/checkout@v2
        with:
          path: 'assumption'

      - name: configuration
        run: cmake -S assumption -B assumption-build -DCMAKE_BUILD_TYPE=Release

      - name: build dependencies
        run: cmake --build assumption-build --target fmt gmock gmock_main gtest gtest_main -j 2

      - name: build
        run: cmake --build assumption-build --target all -j 2

      - name: test
        working-directory: assumption-build
        run: ctest --output-on-failure -j 2